name: vault_converter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.0.0
  get_it: ^7.0.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.7.1


